### ISSUE TITLE
Configuring resources with complex attributes

### ISSUE THREAD

**Issue by evsheffield** [scott-mcdonald/JsonApiFramework#31]
I have a class which has some attributes consisting of arrays of other objects and I am trying to find a way to configure these complex attributes for representation in a JsonApi document. I would like to represent them as JSON objects within the attributes rather than as relations. Specifically, I would like to have my configured conventions apply to these nested objects and be able to set ignores and API property names for their fields. Consider the following example:

**Resource**

```
public class Foo : IResource
{
    public string Id { get; set; }
    public string Name { get; set; }
    public Bar[] Items { get; set; } 
}

public class Bar
{
    public string Value { get; set; }
    public string MyLabel { get; set; }
}
```

**Document Context configuration**

```
public class ReportingDocumentContext : DocumentContext
{
      ...

        protected override void OnConfiguring(IDocumentContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            var conventions = CreateConventionsBuilder();
            optionsBuilder.UseConventions(conventions);
        }

        protected override void OnServiceModelCreating(IServiceModelBuilder serviceModelBuilder)
        {
            var fooConfiguration= serviceModelBuilder.Resource<Foo>();
            fooConfiguration.ResourceIdentity(x => x.Id).SetApiType("foo");
            // How do I configure Bar.MyLabel in Foo.Items?
        }

        private static IConventions CreateConventionsBuilder()
        {
            var conventionsBuilder = new ConventionsBuilder();
            conventionsBuilder.ApiAttributeNamingConventions().AddStandardMemberNamingConvention();
            conventionsBuilder.ResourceTypeConventions().AddPropertyDiscoveryConvention();

            return conventionsBuilder.Create();
        }
}
```

**Document**

```
{
  "data": {
    "type": "foo",
    "id": "123",
    "attributes": {
      "name": "Foo!",
      "items": [
        {
          "Value": "thing1",
          "MyLabel": "label"
        }
      ]
    }
  }
}
```

I would like to be able to configure the `Value` and `MyLabel` attributes to use the same conventions and also be able to provide custom configuration for them. Is there a way to do this? My current workaround for handling API property names involves making the nested `Bar` object a `JsonObject` and configuring the `JsonProperty` for each field, but it would be nice to handle this in the document configuration instead.

**Comment by scott-mcdonald** [comment]
Evan,

What you are asking for is a feature I implemented in this issue #1 which brings in the concept of complex types as part of the framework. I do realize the documentation is lacking describing this feature and thus your question.

> FYI: I am heavily focused on version 2 so when I release version 2 will get back to improving the documentation.

So here is how you use this feature:

You use the class ComplexTypeBuilder<TComplex> which is similar in concept to ResourceTypeBuilder<TResource> but you can only configure attributes of a complex type.

Here is an example for your scenario both assuming no conventions at all and with the conventions:

````csharp
public class BarWithNullConventions : ComplexTypeBuilder<Bar>
{
    public BarWithNullConventions()
    {
        // Attributes
        this.Attribute(x => x.Value)
            .SetApiPropertyName("value");

        this.Attribute(x => x.MyLabel)
            .SetApiPropertyName("my-label");

       // Ignores
       this.Attribute(x => x.SomeProperty)
           .Ignore();
    }
}

public class BarWithConventions : ComplexTypeBuilder<Bar>
{
    public BarWithConventions()
    {   }
}

public class ReportingDocumentContext : DocumentContext
{
      ...

        protected override void OnConfiguring(IDocumentContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            var conventions = CreateConventionsBuilder();
            optionsBuilder.UseConventions(conventions);
        }

        protected override void OnServiceModelCreating(IServiceModelBuilder serviceModelBuilder)
        {
            var fooConfiguration= serviceModelBuilder.Resource<Foo>();
            fooConfiguration.ResourceIdentity(x => x.Id).SetApiType("foo");

            // Notice the adding of the configuration for your 'Bar' complex type assuming the conventions down below.           
            serviceModelBuilder.Configurations.Add(new BarWithConventions());
        }

        private static IConventions CreateConventionsBuilder()
        {
            var conventionsBuilder = new ConventionsBuilder();
            conventionsBuilder.ApiAttributeNamingConventions().AddStandardMemberNamingConvention();
            conventionsBuilder.ResourceTypeConventions().AddPropertyDiscoveryConvention();

            // Notice the complex type conventions being added here...
            conventionsBuilder.ComplexTypeConventions().AddPropertyDiscoveryConvention();

            return conventionsBuilder.Create();
        }
}

````

Let me know how this works for you!

Regards,
Scott McDonald

**Comment by evsheffield** [comment]
Thanks so much for the quick response, Scott!

It wasn't working at first but then I looked through some of your test data and noticed that for multi-valued attributes you were using `List` instead of arrays (as in [StoreConfiguration](https://github.com/scott-mcdonald/JsonApiFramework/blob/master/Tests/JsonApiFramework.Core.TestData/ClrResources/StoreConfiguration.cs)).

I simply changed my `Foo` class to use `List<Bar>` instead and that in combination with your suggestions did the trick.

```
public class Foo : IResource
{
    public string Id { get; set; }
    public string Name { get; set; }
    // changed from Bar[]
    public List<Bar> Items { get; set; } 
}
```

Is that to be expected? It doesn't make a difference for my use case either way, I just want to be sure for when I'm designing future complex types. :)

**Comment by scott-mcdonald** [comment]
@evsheffield The framework should work for any collection type (in theory or so I thought), so I need to write some unit tests to reproduce and then fix the collection type defect as I must be using List in all my unit tests... To be safe, I would recommend using List for now but I do not like having a framework being "restrictive" if it can be helped...
