### ISSUE TITLE
Please provide a working example of parsing JSON into Document

### ISSUE THREAD

**Issue by starnovsky** [scott-mcdonald/JsonApiFramework#33]
The following code is creating an empty document:
`var document = JsonObject.Parse<Document>(json);`

Where json is
`{
  "value": {
    "jsonapi": {
      "version": "1.0"
    },
    "errors": [
      {
        "status": "422",
        "code": "100",
        "title": "is taken",
        "detail": "appointment-at - is taken",
        "source": {
          "Pointer": "/data/attributes/appointment-at"
        }
      }
    ]
  }
} `

Resource documents are also not parsed.

**Comment by starnovsky** [comment]
Interesting enough is that when I'm passing a Document into controller POST method as body, Document is being deserialized successfully.

**Comment by scott-mcdonald** [comment]
@starnovsky Stan, I want to make sure you question was answered. First I have a separate repository with Samples which contains working examples: [Samples](https://github.com/scott-mcdonald/JsonApiFramework.Samples). So between the samples the examples in the README.md file is your question answered?

**Comment by starnovsky** [comment]
Thank you for responding to that, @scott-mcdonald ! 
I have weird issue with deserializing Document from JSON string.
In my Web API project (Core) everything works fine. I can deserialize Document by using either JsonObject or JsonConvert.
However, when I'm writing a unit test (Xunit) for my controller, deserialization doesn't seem to work. I can confirm that I have a valid JSONAPI document (in form of JSON) which is returned by my controller, but when trying to deserialize it into Document, I'm getting an empty Document.
I guess I'm doing something wrong, but I didn't figure out my issue yet.

**Comment by scott-mcdonald** [comment]
@starnovsky All the xUnit tests I wrote for server-side unit testing work but that is for simple POCO classes, but your scenario is different by unit testing the controller directly. I would have to play around with it to see what is going on, let me know what the issue was for my own edification...
