### ISSUE TITLE
Please provide a working example of adding related object to resource without using Included

### ISSUE THREAD

**Issue by starnovsky** [scott-mcdonald/JsonApiFramework#34]
The following code from the documentation is not building for me:
` // Build document
            var document = documentContext
                .NewDocument()
                    // Resource document (convert CLR Article resource to JSON API resource)
                    .Resource(article)
                        // Link new article to an existing author.
                        .Relationships()
                            .AddRelationship("author", authorId)
                        .RelationshipsEnd()
                    .ResourceEnd()
                .WriteDocument();`

**Comment by scott-mcdonald** [comment]
@starnovsky Stan I want to first understand your question. So we are clear, the [json:api](http://jsonapi.org/) specification does not allow resources to be composed of other resources. This topic was also discussed in the json:api forum as well: [Clarification on Resources Composed of Other Resources](http://discuss.jsonapi.org/t/clarification-on-resources-composed-of-other-resources/252). Therefore the only way to get a valid json:api document with related resources is to have the related resources in the Included section.

Also take a look at the [Samples](https://github.com/scott-mcdonald/JsonApiFramework.Samples) repository. That has working examples, let me know if that answers your question, if not then I'll post some examples from the unit tests...

**Comment by starnovsky** [comment]
Thank you, Scott! 
Sorry for not being specific enough...
I',m referring to the following sample: https://github.com/scott-mcdonald/JsonApiFramework/#client-side-document-building-for-post-example
The code in this example is not building for me, I can't find an overload for AddRelatioship extension matching the signature used in this example (i.e. string, long)
I'm trying to create a document which would include a resource with a relationship having a type and id, but not including the related resource itself.
So far I only was able to add a relationship with ID by using Include().

**Comment by scott-mcdonald** [comment]
@starnovsky Now I better understand. Make sure you include JsonApiFramework [Client] not JsonApiFramework [Server] nuget package. JsonApiFramework.Client nuget package is specifically for client-side json:api document building. Once you have JsonApiFramework.Client nuget package, add a using statement for `JsonApiFramework.Client` and you will see the `AddRelationship` method you are trying to use... The `Include` builder method is only available on JsonApiFramework.Server so it looks like it wasn't clear what nuget package goes with the example code in the readme.md file.
