### ISSUE TITLE
.NET Standard/Core support?

### ISSUE THREAD

**Issue by choco1** [scott-mcdonald/JsonApiFramework#35]
`ERROR: One or more packages are incompatible with .NETStandard,Version=v1.4.`
Adding it to a `Class Library`-type solution.
Sorry for any wrong assumptions, but Json.Net is Standard-compatible, so I assume it can't be extremely hard to port? I can contribute.

**Comment by scott-mcdonald** [comment]
I want to be clear what you are asking, you tried using the current JsonApiFramework nuget packages with some .NET Core class library, console app, web api, etc? If so, the current version of JsonApiFramework I have in nuget is of version 1.X and is strictly .NET Framework class libraries and only works with projects that use the .NET Framework.

I am currently working on JsonApiFramework v2.0 which is currently being developed as a .NET Standard Library 1.4 version. This version of the JsonApiFramework v2.0 has a dependency on JSON.NET standard library as well and so far I have had no problems. My understanding is a consumer of JsonApiFramework v2.0 could be anything from a .NET core console app, some Linux application, or a Windows application, etc. This version is being developed in the v2.0 branch.

So did I answer your question?

**Comment by choco1** [comment]
Sweet, thanks!

**Comment by Jetski5822** [comment]
@scott-mcdonald does the 2.0 branch work? I need this lib as a nuget package, are you anyways close to having a release? even a nuget package??

**Comment by scott-mcdonald** [comment]
@Jetski5822 I have been away on vacation so sorry about not immediately replying to your question. The v2.0 branch is a complete rewrite starting from scratch. From the beginning it is being developed as a .NET Standard Library 1.4. It is not complete and usable like the v1.X version which is complete. I also need the v2.0 branch to be complete but have been pulled to other projects. It is only recently where finally I can start getting back to the v2.0 branch. With that said it is at least 6 months away from being production ready. I'll take a look at your pull request over the weekend to see what you have done. Thanks for taking an interest in JsonApiFramework.

**Comment by Jetski5822** [comment]
Hey @scott-mcdonald - no problem, I was looking at this to be the json api server abstraction for Orchard Core (https://github.com/OrchardCMS/Orchard2) - and am struggling to find a dotnet core library at the moment.

I just pushed the lib to the most compatible version I could, which is the best thing to do IMO and only increase the version when pulling in a third party library that requires you do that. So start at 1.0 and work your way up.

**Comment by scott-mcdonald** [comment]
@Jetski5822 Actually a very useful task would be to "port" the current "master" branch of JsonApiFramework to .NET Standard 1.X or .NET Standard 2.0 instead of the 2.0 branch. I am not sure what would be involved in doing that but definitely would make JsonApiFramework 1.X more useful as it is production ready now. What do you think? Something you would be interested in doing?

**Comment by scott-mcdonald** [comment]
Going to reopen and port the current 1.X version of JsonApiFramework to a .NET Standard version. Not sure what version of .NET Standard yet?

**Comment by scott-mcdonald** [comment]
Completed port of master branch to .NET Standard 1.0 and all unit tests pass. Will work on packaging and updating documentation next.

**Comment by Jetski5822** [comment]
@scott-mcdonald nice work man - sorry I havent had any time, mainly cuz I was on holiday hehe.

**Comment by scott-mcdonald** [comment]
Finished preliminary documentation and did some integration testing by enhancing the samples to contain .NET Core applications and verified the new 1.4 version of JsonApiFramework as a .NET Standard class library works just fine in .NET Core apps. Updated the README.MD file as well. More documentation work is needed on the wiki. The port to .NET Standard 1.0 itself was very easy as I didn't need to change a single line of code - not bad if I do say so myself ;-)

JsonApiFramework as a .NET Standard library is now available on nuget.org at the 1.4.0-beta version.
