### ISSUE TITLE
Swagger?

### ISSUE THREAD

**Issue by starnovsky** [scott-mcdonald/JsonApiFramework#37]
What would be the best way to get Document models describable with Swashbuckle? Or to auto-generate swagger docs some other way?

**Comment by scott-mcdonald** [comment]
I am sorry I don't have an answer for you. We have this same problem where I work in creating documentation of the service model for our hypermedia API. And to be honest this aspect has been given lower priority compared to the hypermedia API itself. We have been focusing more on higher level workflow documentation with class and sequence UML diagrams while pointing 3rd part integrators to the json:api website for the low-level "protocol" documentation.

If you fine an elegant solution to this documentation, please share it...
