### ISSUE TITLE
Content-Type (with character-encoding information)

### ISSUE THREAD

**Issue by OKTAYKIR** [scott-mcdonald/JsonApiFramework#40]
I'm sending the following header:

`Content-Type : application/vnd.api+json; charset=utf-8`

I get the following error:

`415 - Unsupported Media Type`

**Comment by scott-mcdonald** [comment]
@OKTAYKIR JsonApiFramework [Server] is agnostic about any high level REST API frameworks, for example WebApi. Therefore you would have to "bootstrap" in JsonApiFramework [Server] into something like WebApi yourself by installing your own media-type formatter. I do intend on creating a higher level framework called JsonApiFramework [WebApi] that integrates JsonApiFramework [Server] into WebApi seamlessly but I haven't gotten around to doing that just yet.

For the example code provided, I did use WebApi but didn't install a media type formatter specifically for JSON API where you would pass `content-type: application/vnd.api+json` instead I relied on the fact the default JsonMediaTypeFormatter uses JSON.NET which is what JsonApiFramework [Server] is built upon for JSON serialization/deserialization. So to keep it simple for now, trying passing `content-type: application/json` instead and it should work as-is. Or write a media type formatter for JsonApiFramework [Server] for whatever high level REST API framework you are using and then you can pass `content-type: application/vnd.api+json` as the desired content type by the client. Does that answer your question?

**Comment by scott-mcdonald** [comment]
@OKTAYKIR Since you gave thumbs up I will consider this issue closed.
