### ISSUE TITLE
Include Resource Linkage Without Needing to Include Related Resources

### ISSUE THREAD

**Issue by cjwyatt** [scott-mcdonald/JsonApiFramework#41]
Hi, I'm trying to write some endpoints to be consumed by ember-data which expects Resource Identifier Objects (RIO) to be returned for relationships so it can asynchronously fetch them on demand.

I know how to use .included() to have RIOs added to the relationships' data section but I can't see how I can do so without including the entire related object. **Is this possible using JsonApiFramework?**

Here's an example of what ember-data is expecting:

```javascript
{
   'type':'restaurant',
   'id':'ed804168-d1f0-4bfc-be56-e93b8cbe8e99',
   'attributes':{
      'title':'HelloFood',
      'contact-number':'555-1234',
      'restaurant-address':'Some Street, Some Area'
   },
   'relationships':{
      'menu-sections':{
         'data':[
            {
               'type':'menu-section',
               'id':'09174b51-31a9-4e44-a89a-d6e734652d9d'
            }
         ]
      }
   }
}
```

**Comment by scott-mcdonald** [comment]
@cjwyatt The quick answer is no in the current version, the only way to include "resource linkage" was by including related resources.

But since you are the 2nd person to inquiry about this topic and I could use this feature as well, I am going to add the ability to create "resource linkage" without needing to include related resources in the next milestone. Look for this new feature in the next week or two.

**Comment by cjwyatt** [comment]
Awesome, thanks.

**Comment by scott-mcdonald** [comment]
@cjwyatt As a quick note, what is interesting is I already support this feature for JsonApiFramework.Client when building of JSON API documents for POST or PATCH purposes. After looking at the code, going to move this ability to the Infrastructure component so it can be shared by both JsonApiFramework.Client and JsonApiFramework.Server backed by unit tests of course.

**Comment by scott-mcdonald** [comment]
Previous commit was not the total solution, only preparation for the solution to come. Note I am going to leave the client-side building with `SetId` as-is. The solution for this issue will directly support server-side manual addition of resource linkage, more commits to come...

**Comment by scott-mcdonald** [comment]
@cjwyatt I have my first success in adding this feature. Need to polish and add more unit tests but feature is less then a week away...

**Comment by scott-mcdonald** [comment]
@cjwyatt This feature request has been completed. Take a look at the readme where I added an usage example of manually adding resource linkage to a resource. Here is a snippet so you can get a feel:

```
.Relationships()
    .Relationship("author")
        .Links()
            .AddSelfLink()
            .AddRelatedLink()
        .LinksEnd()
        .SetData(ToOneResourceLinkage.Create(42))
    .RelationshipEnd()
    .AddRelationship(rel: "comments",
                     linkRelCollection: new []{ "self", "related" },
                     toManyResourceLinkage: ToManyResourceLinkage.Create(new []{ 68, 86 }))
.RelationshipsEnd()
```
_Note_: you can manually add resource linkage by the `SetData` method or in the parameter list of `AddRelationship` as demonstrated above. This feature is in the v1.5.0 version of JsonApiFramework and is available on nuget.org. I have also dropped the `-beta` in the version as it has been about a year in beta so it is time...

**Comment by chris-wyatt-livinglens** [comment]
Look great :) Thanks again.

**Comment by cjwyatt** [comment]
Looks great :smile:  Thanks again.

**Comment by theblomskog** [comment]
Hi! Realy usefull feature and it works nice with a single resource document. But I can't get it to work with a recource collection. Am I missing something or is it not supported. In my case it would be most usefull in a collection document.

**Comment by scott-mcdonald** [comment]
@theblomskog So yes I do need better "API documentation" for questions like this. But yes it does work with a resource collection document, you just have to pass an IEnumerable of either to-one or to-many resource linkage objects. Just make sure the counts are the same otherwise an exception will be thrown.

Here is a snippet from one of the unit tests to demonstrate manually adding resource linkage in a couple of different ways:

```
DocumentBuilderFactory.Create(ClrSampleData.ServiceModelWithBlogResourceTypes, HypermediaAssemblerRegistry, UrlBuilderConfigurationWithoutRootPathSegments, ApiSampleData.ArticleCollectionHRef)
    .SetJsonApiVersion(ApiSampleData.JsonApiVersionAndMeta)
    .SetMeta(ApiSampleData.DocumentMeta)
    .Links()
        .AddLink(Keywords.Self)
    .LinksEnd()
    .ResourceCollection(new []{ SampleArticles.Article1, SampleArticles.Article2 })
        .SetMeta(ApiSampleData.ResourceMeta, ApiSampleData.ResourceMeta)
        .Relationships()
            .AddRelationship(ApiSampleData.ArticleToAuthorRel, new []{ Keywords.Self, Keywords.Related}, new [] { ToOneResourceLinkage.Create(ApiSampleData.PersonId1), ToOneResourceLinkage.Create(ApiSampleData.PersonId2) })
            .Relationship(ApiSampleData.ArticleToCommentsRel)
                .Links()
                    .AddSelfLink()
                    .AddRelatedLink()
                .LinksEnd()
                .SetData(new [] { ToManyResourceLinkage.Create(new[] { ApiSampleData.CommentId1, ApiSampleData.CommentId2 }), ToManyResourceLinkage.Create(new[] { ApiSampleData.CommentId3, ApiSampleData.CommentId4 }) })
            .RelationshipEnd()
        .RelationshipsEnd()
        .Links()
            .AddLink(Keywords.Self)
            .AddLink(Keywords.Canonical)
        .LinksEnd()
    .ResourceCollectionEnd()

```
This should do the trick...

**Comment by theblomskog** [comment]
Works like a charm. Thank you wery much.

**Comment by scott-mcdonald** [comment]
@theblomskog Glad it worked well for you. Please star the project if you find the project "star worthy" for your json:api related projects...

**Comment by wayne-o** [comment]
Hope you don’t mind if I chime in here..

This is the best JSON API framework for .net without doubt

Your commitment to it is outstanding.

Thank you, Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
