### ISSUE TITLE
Add Non-Generic Reading of Resources to DocumentContext

### ISSUE THREAD

**Issue by cjwyatt** [scott-mcdonald/JsonApiFramework#45]
Hi Scott,

I'm trying to write a custom formatter for an ASP.NET Core app and I've run into a bit of an issue. I'm able to extract the JSON from the request and parse it into a document and then create the DocumentContext with that document but when it comes to calling GetResource to extract the resource object I have to call a generic method but I only have the target type as a Type.

Obviously I could use reflection to invoke the method but that's not very performant. Is there another way at all?

**Comment by scott-mcdonald** [comment]
@cjwyatt Do not use reflection as you are correct it does not have good performance. Internally I am getting the `Type` of `TResource` with the `typeof` operator and finding the resource(s) in the DOM tree by `Type`. Unfortunately I did not expose the non-generic versions of getting resources by `Type` but should be easy to add as that is what I am doing internally.

This will be a nice enhancement that I should have exposed from the beginning. Give me 2-3 days and I'll add this feature and put it up on **nuget.org** as version 1.5.1.

Thanks,
Scott

**Comment by chris-wyatt-livinglens** [comment]
Awesome, thanks Scott!

**Comment by scott-mcdonald** [comment]
@cjwyatt Wanted to give an update. I have finished with my implementation of this feature and all the current unit tests pass. I want to add some more unit tests around the new methods added to `IDocumentReader` to be specific, etc. before building and deploying to nuget.org. Look for a deployment of 1.5.1 to nuget.org no later then tomorrow night sometime.

**Comment by scott-mcdonald** [comment]
@cjwyatt This feature is complete. Note because this feature added new methods to the current interface of DocumentContext via the IDocumentReader abstraction, I renamed the intended version from 1.5.1 to 1.6.0 because of the public facing interface addition. I did push version 1.6.0 of JsonApiFramework up to nuget.org. Let me know how it works out for you...

**Comment by cjwyatt** [comment]
Thanks Scott, I've implemented my custom formatter now using the non-generic interface and it works great :smile:

**Comment by scott-mcdonald** [comment]
@cjwyatt Awesome news, glad it worked the first time!
