### ISSUE TITLE
Unexpected DocumentContext.GetResourceRelationships() behaviour

### ISSUE THREAD

**Issue by cjwyatt** [scott-mcdonald/JsonApiFramework#46]
Hi Scott,

I'm writing an endpoint to handle POST requests for a new resource that needs to be linked to an existing resource on creation. I'm using a resource identifier relationship (I think that's the right terminology) to set the parent of the newly created resource.

My problem is that GetResourceRelationships() is returning null if the id isn't a valid guid. That is:

{
  "data": {
    "id": "00000000-0000-0000-0000-000000000000",
    "attributes": {
      "food-name": "Pie and Chips",
      "price": 300,
      "description": null,
      "is-vegetarian": false,
      "is-hot": false,
      "contains-nuts": false,
      "order": 2
    },
    "relationships": {
      "menu-section": {
        "data": {
          "type": "menu-section",
          "id": "1f49662b-00a3-11e8-aaf1-08002787e7fb"
        }
      }
    },
    "type": "menu-item"
  }
}

will correctly return a relationship but:

{
  "data": {
    "id": null
    "attributes": {
      "food-name": "Pie and Chips",
      "price": 300,
      "description": null,
      "is-vegetarian": false,
      "is-hot": false,
      "contains-nuts": false,
      "order": 2
    },
    "relationships": {
      "menu-section": {
        "data": {
          "type": "menu-section",
          "id": "1f49662b-00a3-11e8-aaf1-08002787e7fb"
        }
      }
    },
    "type": "menu-item"
  }
}

or omitting id entirely returns null. Reading the spec it sounds like a client-generated id is optional so I shouldn't need to send one.

Your thoughts?

**Comment by scott-mcdonald** [comment]
@cjwyatt 
I reformatted both of your examples just so it was easier to read:
```js
{
  "data": {
    "type": "menu-item",
    "id": "00000000-0000-0000-0000-000000000000",
    "attributes": {
      "food-name": "Pie and Chips",
      "price": 300,
      "description": null,
      "is-vegetarian": false,
      "is-hot": false,
      "contains-nuts": false,
      "order": 2
    },
    "relationships": {
      "menu-section": {
        "data": {
          "type": "menu-section",
          "id": "1f49662b-00a3-11e8-aaf1-08002787e7fb"
        }
      }
    }
  }
}
````
and
````js
{
  "data": {
    "type": "menu-item",
    "id": null,
    "attributes": {
      "food-name": "Pie and Chips",
      "price": 300,
      "description": null,
      "is-vegetarian": false,
      "is-hot": false,
      "contains-nuts": false,
      "order": 2
    },
    "relationships": {
      "menu-section": {
        "data": {
          "type": "menu-section",
          "id": "1f49662b-00a3-11e8-aaf1-08002787e7fb"
        }
      }
    }
  }
}
````
So first of all nothing is wrong with either of the json:api documents for a POST. The `id` being set or not set should absolutely have no bearing on whether `GetResourceRelationships` works. I am going to write a unit test and verify the defect and if so will fix it immediately.

**Comment by cjwyatt** [comment]
Hi Scott,

This is the code I'm using. Let me know if you need more context:

```
var resource = ctx.GetResource(resourceType);
var links = ctx.GetResourceLinks(resource);
var relationships = ctx.GetResourceRelationships(resource);
```

**Comment by scott-mcdonald** [comment]
@cjwyatt 

So this is a lack of documentation, but on the server side of a POST which is a standard use case were the identifier is not passed, the server code will typically only have a single resource with no identifier as the primary data which you look up by "type" like you did in the first call to get the resource to create; the same overload applies for the links and relationships. The other two calls try to lookup "links" and "resources" by **identity** because you passed a resource object which is typically a client-side thing to do from a GET call to the server...

So something like this is what you need:
```js
var resource = ctx.GetResource<MenuItem>(); // or
var resource = ctx.GetResource(typeof(MenuItem));

var links = ctx.GetResourceLinks<MenuItem>(); // or
var links = ctx.GetResourceLinks(typeof(MenuItem));

var relationships = ctx.GetResourceRelationships<MenuItem>(); // or
var relationships = ctx.GetResourceRelationships(typeof(MenuItem));
```

Hope that makes sense and helps...

**Comment by cjwyatt** [comment]
Hi Scott,

Unfortunately this is code inside my custom formatter which doesn't know anything about the types inside the request. For reference here is the complete formatter code:

```
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ChamuBackend.JsonApi;
using ChamuBackend.JsonApi.Resources;
using JsonApiFramework;
using JsonApiFramework.JsonApi;
using JsonApiFramework.Reflection;
using JsonApiFramework.ServiceModel;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.Net.Http.Headers;
using JsonObject = JsonApiFramework.Json.JsonObject;
using TypeExtensions = System.Reflection.TypeExtensions;

namespace ChamuBackend.CustomFormatters
{
    public class JsonApiInputFormatter : TextInputFormatter
    {
        public JsonApiInputFormatter()
        {
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("application/vnd.api+json"));

            SupportedEncodings.Add(Encoding.UTF8);
            SupportedEncodings.Add(Encoding.Unicode);
        }

        protected override bool CanReadType(Type type)
        {
            // TODO: Check for resource types
            return true;
        }

        public override async Task<InputFormatterResult> ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
        {
            var targetType = context.ModelType;

            using (var reader = new StreamReader(context.HttpContext.Request.Body, encoding))
            {
                try
                {
                    var json = await reader.ReadToEndAsync();

                    if (targetType == typeof(string))
                    {
                        return InputFormatterResult.Success(json);
                    }

                    var document = JsonObject.Parse<Document>(json);

                    using (var ctx = new ApplicationDocumentContext(document))
                    {
                        if (typeof(IResource).IsAssignableFrom(targetType))
                        {
                            var resource = ctx.GetResource(targetType);

                            return InputFormatterResult.Success(resource);
                        }

                        if (targetType.IsGenericType() && targetType.GetGenericTypeDefinition() == typeof(ResourceWithMeta<>))
                        {
                            var resourceType = TypeExtensions.GetGenericArguments(targetType).First();
                            
                            var resource = ctx.GetResource(resourceType);
                            var links = ctx.GetResourceLinks(resource);
                            var relationships = ctx.GetResourceRelationships(resource);

                            var result = Activator.CreateInstance(targetType, resource, relationships, links);

                            return InputFormatterResult.Success(result);
                        }
                    }

                    throw new ArgumentException("Unknown target type");
                }
                catch (Exception ex)
                {
                    return await InputFormatterResult.FailureAsync();
                }
            }
        }
    }
    
    public class ResourceWithMeta<T> where T : class, IResource
    {
        public ResourceWithMeta(T resource, Relationships relationships, Links links)
        {
            Resource = resource;
            Relationships = relationships;
            Links = links;
        }

        public Relationships Relationships { get; set; }
        public Links Links { get; set; }
        public T Resource { get; set; }
    }
}
```

**Comment by scott-mcdonald** [comment]
@cjwyatt 

Try the following inside 

`public override async Task<InputFormatterResult> ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding):`

````js
var resourceType = TypeExtensions.GetGenericArguments(targetType).First();
                            
var resource = ctx.GetResource(resourceType);
// var links = ctx.GetResourceLinks(resource);
// var relationships = ctx.GetResourceRelationships(resource);
var links = ctx.GetResourceLinks(resourceType);
var relationships = ctx.GetResourceRelationships(resourceType);


var result = Activator.CreateInstance(targetType, resource, relationships, links);

return InputFormatterResult.Success(result);
````

**Comment by cjwyatt** [comment]
Ah I see, I must have misunderstood your earlier response. I thought you were saying I had to pass in the type of the relationship you wanted rather than the type of resource in the request. Thanks I'll give this a try tonight.

**Comment by cjwyatt** [comment]
Worked like a charm. Thanks again Scott.
