### ISSUE TITLE
Possible to customize link templates?

### ISSUE THREAD

**Issue by cmeeren** [scott-mcdonald/JsonApiFramework#49]
I have a resource of type `Order`. I serve these under `/orders/{orderId}`. Each order has many `OrderLine` objects. Since these do not make sense on their own but only as part of an order, I want to serve them under `/orders/{orderId}/{lineNumber}`. Is it possible to configure this using JsonApiFramework?

**Comment by scott-mcdonald** [comment]
I believe what you are asking for is something like this:

````cs
public class Order : IResource
{
    public string OrderId { get; set; }
}

public class OrderItem : IResource
{
    public string OrderItemId { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
}

public class OrderConfigurationWithConventions : ResourceTypeBuilder<Order>
{
    public OrderConfigurationWithConventions()
    {
        // Relationships
        this.ToManyRelationship<OrderItem>("line-items");
    }
}

public class OrderItemConfigurationWithConventions : ResourceTypeBuilder<OrderItem>
{
    public OrderItemConfigurationWithConventions()
    {  }
}

// Building orders would look something like this:

// GET /orders/{orderId}

var order = GetOrder(orderId);

var document = documentContext
    .NewDocument(currentRequestUrl)
        .Resource(order)
            .Relationships()
                .AddRelationship("line-items", new [] { "related" })
            .RelationshipsEnd()
            .Links()
                .AddLink("self")
            .LinksEnd()
        .ResourceEnd()
    .WriteDocument();

// And for the implementation for the "related" link to get all the line items

// GET /orders/{orderId}/line-items

var order = GetOrder(orderId)
var orderLineItems = GetOrderLineItems(orderId);

var document = documentContext
    .NewDocument(currentRequestUrl)
        .ResourceCollection(orderLineItems)
            .Paths()
                .AddPath(order, "line-items") // Or the following AddPath flavor
                .AddPath<Order, string>(orderId, "line-items")
            .PathsEnd()
            .Links()
                .AddLink("self")
            .LinksEnd()
        .ResourceEnd()
    .WriteDocument();

// The "Paths" fluent building adds paths to the hypermedia being built by the
// hypermedia generation for respective resources.
// This would cause all the order items to have "self" links like the following:

// \orders\1\line-items\1
// \orders\1\line-items\2
// \orders\1\line-items\3
// \orders\1\line-items\4

// I use this when a resource is like a true child of a parent resource and must always
// be under the parent resource like order and order items is a prototypical example.

````

**Comment by cmeeren** [comment]
Thanks, I didn't know about `Paths`. Two problems, though (note that I'm not currently using JsonApiFramework, so you don't need to spend much time on this if you have better things to do):

1. I want to drop `/line-items` from the URL and just use `/orders/1/1`, `/orders/1/2` etc. The rationale behind this is that order lines are the primary sub-items of an order, so it "looks nicer" if one doesn't have to add `line-items`.

2. The line number I want to use in the URL is only unique in the context of a given order. In your example, you seem to expect that `OrderItemId` is globally unique in the API. For example, `/orders/1/1` and `/orders/2/1` points to two different order lines. This must of course be reconciled with the resource needing a globally unique ID (otherwise an endpoint returning multiple orders with included order lines will return colliding resources). So the resource ID (globally unique) needs to be something other than what is placed in the URL (the order-specific line number).

Please also let me know if you think there are good reasons why the approach I just described is bad.

**Comment by scott-mcdonald** [comment]
I would recommend you follow the json:api specification and use the "line-items" as a path segment under "orders" for the following reasons:

- It follows the json:api standard for relationships as what you are doing is non-standard. For example an order resource would look something like this:

````js
{
  "type": "orders",
  "id": "1",
  "relationships": {
    "order-items": {
      "links": {
        "self": "/orders/1/relationships/line-items",
        "related": "/orders/1/line-items"
      }
    }
  },
  "links": {
    "self": "/orders/1"
  }
}
````
Now look at the "related" link in the "order-items relationship `/orders/1/line-items` it gives the client the hypermedia link to get **ALL** the related line-items for something like `GET /orders/1/line-items`. With your approach how would you get all "line items" in a GET call. Now if you want line items to be a true "child" of order then their individual "self" links would be built under the parent order resource, something like:
```
/orders/1/line-items/1
/orders/1/line-items/2
```

Now let's say have a relationship to payments
````js
{
  "type": "orders",
  "id": "1",
  "relationships": {
    "order-items": {
      "links": {
        "self": "/orders/1/relationships/line-items",
        "related": "/orders/1/line-items"
      }
    },
    "payments": {
      "links": {
        "self": "/orders/1/relationships/payments",
        "related": "/orders/1/payments"
      }
    },
  },
  "links": {
    "self": "/orders/1"
  }
}
````

Now you have a "related" link to get ALL the payments associated to an order: `/orders/1/payments`. Now I would think you wouldn't want payments to be a "child" of order then their individual "self" links would be built at the "root" level, something like:

```
/payments/1234
/payments/5678
```
- You say it is "nicer" but personally I find `/orders/1/2` harder to read or less self-documenting than `/orders/1/line-items/2`. Now if you were a 3rd party integrator developing against your API what would be easier to understand?

- In the end if you want consumers to use your API, stick to the standard of what the json:api specification states.

Good luck on your project!

**Comment by scott-mcdonald** [comment]
I will give you 1 more reason why I would put "line-items". Let's say you have another child resource under order such as you want to keep an audit trail of all changes made to the order, something like:
````cs
{
  "type": "orders",
  "id": "1",
  "relationships": {
    "order-items": {
      "links": {
        "self": "/orders/1/relationships/line-items",
        "related": "/orders/1/line-items"
      }
    },
    "changes": {
      "links": {
        "self": "/orders/1/relationships/changes",
        "related": "/orders/1/changes"
      }
    },
  },
  "links": {
    "self": "/orders/1"
  }
}
````
Now if you want changes to be a true "child" of order then their individual "self" links would be built under the parent order resource, something like:

```
/orders/1/changes/1234
/orders/1/changes/5678
```
without having "sub paths" like "line-items" or "changes" you wouldn't be able to have these true child resources with your initial approach...

By definition it would make sense for "line-items" and "changes" to be true children of order so that if the parent order is deleted all child resources would be deleted as well such as "line-items" and "changes". Payments you would not want to be a child as you never delete a payment so it is at the root, etc...

Anyways with the "Paths" feature of JsonApiFramework document building you are able to create child hypermedia links like you requested so I am going to close this issue...

**Comment by cmeeren** [comment]
Thanks. What you say makes sense. We might have to reconsider our approach to choosing paths.
