### ISSUE TITLE
Custom JSON converters when deserializing documents

### ISSUE THREAD

**Issue by cmeeren** [scott-mcdonald/JsonApiFramework#53]
I've hit an issue similar to #45.

I use F#, and all of my resources fields are wrapped in `Option` (somewhat like Nullable). I have a custom JSON converter to convert `option`-wrapped values to/from normal JSON values. However, I can't seem to get it to work in any way when deserializing with JsonApiFramework. Serialization works fine, and I can deserialize raw JSON to `Document`, but when I deserialize to a specific resource using `DocumentContext.GetResource<MyResource>()`, I get the following exception:

    JsonApiFramework.Reflection.TypeConverterException:
      'Unable to convert from JValue to FSharpOption`1'

My interpretation is that the custom converter is applied when deserializing to `Document`, which has no concept of the type of the resource's fields, and when I subsequently call `GetResource<MyResource>()`, it doesn't know about the custom JSON converter and thus can't figure out how to deserialize to `MyResource`.

Is there a solution to this?

**Comment by scott-mcdonald** [comment]
@cmeeren JsonApiFramework has a feature called "complex types" which should save anybody from having to write any JsonConverter classes. Looking at the documentation I see I have not written any documentation on how to use it. So here it goes.

Complex types are configured similar to Resource types except they are much simpler in that they only contain attributes. They are intended to be used in the attributes section of a Resource or in the attributes of another complex type. They are configured similar to Resource types with the class ComplexTypeBuilder and added as a configuration just like Resource types.

An example
````cs
// Here is the C# of a mailing address complex type:
public class MailingAddress
{
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string ZipCode { get; set; }
}

// Here is the configuration of mailing address with no **conventions**
public class MailingAddressConfigurationWithNullConventions : ComplexTypeBuilder<MailingAddress>
{
    public MailingAddressConfigurationWithNullConventions()
    {
        // Attributes
        this.Attribute(x => x.Address).SetApiPropertyName("address");
        this.Attribute(x => x.City).SetApiPropertyName("city");
        this.Attribute(x => x.State).SetApiPropertyName("state");
        this.Attribute(x => x.ZipCode).SetApiPropertyName("zip-code");
    }
}

// Here is the configuration of mailing address with the typical conventions for
// - property auto discovery
// - standard json:api member naming
public class MailingAddressConfigurationWithConventions : ComplexTypeBuilder<MailingAddress>
{ }

// Here is an example resource where I used complex types of mailing address and phone number
public class Store : IResource
{
    public string StoreId { get; set; }
    public bool IsLive { get; set; }
    public MailingAddress MailingAddress { get; set; }
    public List<PhoneNumber> PhoneNumbers { get; set; }
}

// And lastly here is the document context
public class OrderServiceModelWithConventionsDocumentContext : DocumentContextBase
{
    #region DocumentContextBase Overrides
    protected override void OnConventionsCreating(IConventionsBuilder conventionsBuilder)
    {
        Contract.Requires(conventionsBuilder != null);

        conventionsBuilder.ApiAttributeNamingConventions()
                          .AddStandardMemberNamingConvention();

        conventionsBuilder.ApiTypeNamingConventions()
                          .AddPluralNamingConvention()
                          .AddStandardMemberNamingConvention();

        conventionsBuilder.ComplexTypeConventions()
                          .AddPropertyDiscoveryConvention();

        conventionsBuilder.ResourceTypeConventions()
                          .AddPropertyDiscoveryConvention();
    }

    protected override void OnServiceModelCreating(IServiceModelBuilder serviceModelBuilder)
    {
        Contract.Requires(serviceModelBuilder != null);

        serviceModelBuilder.Configurations.Add(new MailingAddressConfigurationWithConventions());
        serviceModelBuilder.Configurations.Add(new PhoneNumberConfigurationWithConventions());

        serviceModelBuilder.Configurations.Add(new OrderConfigurationWithConventions());
        serviceModelBuilder.Configurations.Add(new OrderItemConfigurationWithConventions());
        serviceModelBuilder.Configurations.Add(new PaymentConfigurationWithConventions());
        serviceModelBuilder.Configurations.Add(new PosSystemConfigurationWithConventions());
        serviceModelBuilder.Configurations.Add(new ProductConfigurationWithConventions());
        serviceModelBuilder.Configurations.Add(new StoreConfigurationWithConventions());
    }
    #endregion
}
````
Therefore I believe if you define `Option` as a complex type you will not need any of your custom JsonConverter classes. Let me know if this does not solve your problem...

/Scott

**Comment by cmeeren** [comment]
Thanks for the tip. Unfortunately we moved on from using JsonApiFramework to instead using a custom designed framework that better fits our needs. I regret to say I am unable to prioritize getting to the bottom of this.

I would guess, however, that it doesn't work, because `Option` is an F# built-in discriminated union, and not something I have control over or that can be modeled as a resource.

**Comment by scott-mcdonald** [comment]
Understood, good luck on your project - the right tool for the right job! Until somebody else asks me about F# going to close this issue for now...
