### ISSUE TITLE
Add support for pascal case and custom naming conventions

### ISSUE THREAD

**Issue by lol768** [scott-mcdonald/JsonApiFramework#71]
I've written this:

```csharp
class PascalCaseNamingConvention : INamingConvention
{
    public string Apply(string oldName)
    {
        return string.IsNullOrWhiteSpace(oldName) ? oldName : oldName.Pascalize();
    }
}
```

But how do I actually use it without reflection?

Does `JsonApiFramework.Conventions.Internal.NamingConventionsBuilder#NamingConventions` actually need to be private?

**Comment by scott-mcdonald** [comment]
I would say the following 2 things to support Pascal naming convention:
1. Add the method `AddPascalCaseNamingConvention` to the `INamingConventionsBuilder` abstraction and respective implementation. Then in the implementation add the new `PascalCaseNamingConvention` instance, basically follow the add known naming conventions pattern already in place.
2. I should have also added a `AddCustomNamingConvention` method which takes a `INamingConvention` parameter to the `INamingConventionsBuilder` abstraction and respective implementation which then would allow the addition of any custom naming convention without any code modification.

These 2 things would be trivial to do and take me about 10 minutes. Give me a couple of days and I'll add it and publish to nuget.org, etc.

**Comment by scott-mcdonald** [comment]
@lol768 FYI, v2.4.0 has been published to nuget which contains this pull request...

**Comment by lol768** [comment]
Thanks @scott-mcdonald!
