### ISSUE TITLE
Inheritance: Properties from base class are not being recognized

### ISSUE THREAD

**Issue by RichardsonWTR** [scott-mcdonald/JsonApiFramework#75]
I'm having problems when I add inheritance.

E.g. this is the file [`Article.cs` from the samples repo](https://github.com/scott-mcdonald/JsonApiFramework.Samples/blob/4df48211c461f96afa901fc187fe0379ab09261a/Tutorials/Blogging/Blogging.ServiceModel.NetCore/Article.cs)
```C#
namespace Blogging.ServiceModel
{
    public class Article
    {
        public long BlogId { get; set; }
        public long AuthorId { get; set; }

        public long ArticleId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    }
}

```

If make a small change  everything breaks

```C#

namespace Blogging.ServiceModel
{
    public class Article : BaseArticle
    {
        public long BlogId { get; set; }
        public long AuthorId { get; set; }

        public string Title { get; set; }
        public string Text { get; set; }
    }

    public abstract class BaseArticle
    {
        public long ArticleId { get; set; }
    }
}
```

When I request `/articles/1` the following error is thrown:
```
An unhandled exception occurred while processing the request.
ServiceModelException: JsonApiFramework.ServiceModel.Internal.ResourceType [clrType=Article] has missing ResourceIdentityInfo metadata. Ensure metadata is configured correctly for the respective domain/schema.
JsonApiFramework.ServiceModel.Configuration.ResourceTypeBuilder<TResource>.CreateResourceIdentityInfo(IConventions conventions)
```

A workaround can be made. It works but it doesn't look good:

```c#
namespace Blogging.ServiceModel
{
    public class Article : BaseArticle
    {
        public long BlogId { get; set; }
        public long AuthorId { get; set; }

        public long ArticleId { get { return BaseArticleId; } set { BaseArticleId = value; } }
        public string Title { get; set; }
        public string Text { get; set; }
    }

    public abstract class BaseArticle
    {
        public long BaseArticleId { get; set; }
    }
}
```

I realized that for every property in the base class I also need to put the property in the inherited class.  
If I don't declare the base class property in the inherited class like shown above the property wont be returned in the response.  
*E.g: Move only the `Text` property to the `BaseArticle` class. It wont be returned when you go to `/articles/1`*

I also cant declare a `ResourceTypeBuilder` for `BaseArticle` since it's `abstract`. If I try this the following error is thrown:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: Can't compile a NewExpression with a constructor declared on an abstract class
System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression(Expression expr)
```

I'm using .net core 3.1.101 and JsonApiFramework 2.4.0

Thanks in advance.
Best regards.

**Comment by scott-mcdonald** [comment]
@RichardsonWTR I'll get back to you soon, was away...

**Comment by scott-mcdonald** [comment]
I will start by saying this is by design for the property discovery convention you are using. The property discovery convention will only look at direct, public, and instance properties for the respective type. The rationale for that behavior was how would the framework know as it is reflecting up the class hierarchy what properties it should include and which ones it should not include. This has not been a problem at least for me as the schema for json:api API's I have been developed have been "flat" and there is no inheritance.

With that said, this would be fairly easy to add if it provides value to consumers of the framework. If you think this will add actual value then let me know and I'll add this feature to the next version. In the meantime if this is some kind of impediment, you could always turn off the property discovery convention and manually configure all properties directly whether they are inherited or directly in your concrete type.

**Comment by RichardsonWTR** [comment]
First, thank you for your support and your detailed answer.
Now I understand more how the property discovery system works.  

Thanks for the insights given. Calling the `Attribute` method for all parent class properties worked as expected.   
But If you want to enhance this system, I think it would be nice to be able define the parent class inside the `ResourceTypeBuilder<T>` by calling a method named `HasBaseType(Type t)`, for example.

**Comment by RichardsonWTR** [comment]
### Related info
#### Using the above approach had led me to the following situation: 
Imagine an abstract base class named `Shape` and 2 inherited classes, `Circle` and `Square`.
The service model builder defines `Circle` and `Shape` classes but not `Shape`, since it's abstract.

If you wanted to return a collection with all shapes (e.g, `/shapes` endpoint), how would you do it?

**How I did it?**
I coudn't pass the `shapes` list to the method `ResourceCollection`, because there's no  `ResourceTypeBuilder` for `Shape`.   
So I 'got my hands dirty' and tried the following solution:   
I created different documents: 
 * the first with the `ResourceCollection` of `Shape` 
 * the last with a `ResourceCollection` of `Circle`  

Then I transformed everything to a json string, parsed it, concatenated the two lists and returned the result.  
The code doesn't look elegant, but it worked. Just sharing the experience. I think returning such list is not against Json API spec.  
What do you think of all this?

**Comment by scott-mcdonald** [comment]
So question on your previous scenario, what would the **primary** data resources look like for the `/shapes` endpoint? Would you expect just the `Shape` resources with just `Shape` attributes and relationships or a heterogeneous collection of `Circle` and `Square` resources with their respective attributes and relationships in the primary data section?

Also I don't think you need to define a `HasBaseType` method, I would just reflect up the class hierarchy grabbing all inherited public and instance based properties as you go up the class hierarchy.

**Comment by RichardsonWTR** [comment]
> So question on your previous scenario, what would the primary data resources look like for the /shapes endpoint?

Very good question. I fogot to mention this detail.  
In my case, I would return a heterogeneous collection of `Circle` and `Square` objects.  
But in another situation I could return only the base class attributes. If  `Shape` class wasn't abstract, for example.   
Maybe the user could choose between these two options.

> Also I don't think you need to define a HasBaseType method, I would just reflect up the class hierarchy grabbing all inherited public and instance based properties as you go up the class hierarchy.

At this moment I don't know how I would implement this (probably changing something inside `ResourceCollection` method or its dependencies), but it sounds amazing.   
Implementing this solution you could just pass a list of `Shape` to `ResourceCollection`? If so, I think it's a perfect solution.

**Comment by scott-mcdonald** [comment]
So I am going to say returning a heterogeneous collection of resources in the primary data part of a json:api document breaks the standard which is where I thought you were going to go. The primary data needs to be homogeneous and should be something from either the /circles or /squares endpoints and return circle and square resources respectively. The /shapes endpoint should only return shape resources respectively, etc. The json:api specification is a flat specification where the concept of "inheritance" makes no sense...

I could see using a baseclass resource only for capturing the commonality between multiple resources but I would make that baseclass abstract and make sure it follows the "is-a" domain modeling. I would also say there should be discrete endpoints for each concrete type inheriting from this baseclass...

**Comment by RichardsonWTR** [comment]
So that's the reason I had so much problems! The spec itself is not meant to work this way.  
This subject is well discussed in Json API repo [#862 Multiple/Hierarchical Types](https://github.com/json-api/json-api/issues/862) and [#28 Polymorphic types](https://github.com/json-api/json-api/issues/28).  
It's time for me to stop and think about the solution I am trying to solve here.
I feel that I wasted our time with this. Sorry.   
Again, thanks for your support. You're doing a great job.
