### ISSUE TITLE
Ability to define relationship with item types defined in enum on client side

### ISSUE THREAD

**Issue by laazik** [scott-mcdonald/JsonApiFramework#92]
Maybe it's a lack of documentation, or my understanding, but I have been unable to figure out how to create a client side POST document, for a scenario where the relationship object can have multiple different objects related to it (e.g. classes deriving from the same base class). For example to define 3 different animals living in the same house:
```json
"data" : {
        "type": "house",
        "id": "5a9d77f7-bdda-4267-8584-ccb1c08e0e07",
},
"relationships": {
    "animals": {
        "data": [
            { "type": "dog", "id": "3284690a-5e07-4442-ae2a-aab057075f2a" },
            { "type": "cat", "id": "a105c330-3ad7-4a61-8a1a-a71fb0114e3d" },
            { "type": "rabbit", "id": "23deecc6-3497-4a4f-a6df-ecf065a38502" }
        ]
    }
}
```
In `ToManyRelationship` configuration I can define that `animals` is either type of `dog`, `cat` or `rabbit` and when creating a document with ID's it is automatically set so, but not sure if I can somehow say that it can be any of these or set the type manually when creating the document. Parsing is also quite tricky.

The schema definition contains an enum definition that allows this object to be as given earlier:
```json
"animal": {
    "type": "object",
    "properties": {
        "data": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["type", "id"],
                "properties": {
                    "type": {
                        "type": "string",
                        "title": "Referenced resource",
                        "enum" : ["cat", "dog", "rabbit"]
                    },
                    "id": {
                        "type": "string",
                        "title": "Resource ID",
                    }
                }
            }
        }
    }
}
```

**Comment by scott-mcdonald** [comment]
@laazik `JSON:API` spec does not support what you are trying to do. It has no concept of inheritance per-se. Therefore you have 2 possible solutions to accomplish what you want to do:

Use something analogous to [Single Table Inheritance](https://www.martinfowler.com/eaaCatalog/singleTableInheritance.html) from the ORM world to essentially have a single resource with `type` **animal** and `attributes` that contain the union of all possible properties for **cat**, **dog**, **rabbit**, etc. Somewhere in the animal resource `JSON:API attributes` you would have a "kind" enumeration or something similar of exactly what type of animal it is. BTW you can't use the attribute name `type` in the `attributes` per the `JSON:API` specification so I typically use the name "kind" for this purpose usually. Your POST/PATCH document when then be something like:

```
"data" : {
        "type": "house",
        "id": "5a9d77f7-bdda-4267-8584-ccb1c08e0e07",
},
"relationships": {
    "animals": {
        "data": [
            { "type": "animal", "id": "3284690a-5e07-4442-ae2a-aab057075f2a" },
            { "type": "animal", "id": "a105c330-3ad7-4a61-8a1a-a71fb0114e3d" },
            { "type": "animal", "id": "23deecc6-3497-4a4f-a6df-ecf065a38502" }
        ]
    }
}
```

which relates the given house to 3 animals of any kind...

Use something analogous to [Concrete Table Inheritance](https://www.martinfowler.com/eaaCatalog/concreteTableInheritance.html) from the ORM world to essentially have a unique resource for each type of animal where the house resource would have to have a unique named relationship for each type of animal as well.

Your POST/PATCH document when then be something like:

```
"data" : {
        "type": "house",
        "id": "5a9d77f7-bdda-4267-8584-ccb1c08e0e07",
},
"relationships": {
    "cats": {
        "data": [
            { "type": "cat", "id": "cat_1" },
            { "type": "cat", "id": "cat_2" },
            { "type": "cat", "id": "cat_3" }
        ]
    },
    "dogs": {
        "data": [
            { "type": "dog", "id": "dog_1" },
            { "type": "dog", "id": "dog_2" },
            { "type": "dog", "id": "dog_3" }
        ]
    },
    "rabbits": {
        "data": [
            { "type": "rabbit", "id": "rabbit_1" },
            { "type": "rabbit", "id": "rabbit_2" },
            { "type": "rabbit", "id": "rabbit_3" }
        ]
    }
}
```

which relates the given house to 3 cats, 3 dogs, and 3 rabbits...

Hope this helps you...

**Comment by laazik** [comment]
Hmm, according to some discussions on the JSON:API website (e.g. https://discuss.jsonapi.org/t/relationship-array-of-different-types-jsonapi-serializer/1723 ) it is something that the JSON:API itself should support (maybe the inheritance was not the best way to express myself). 

Unfortunately I don't have any control over the producing API (based on Drupal), so I'll keep on thinking/digging :).

**Comment by scott-mcdonald** [comment]
@laazik No problem. My comments on inheritance still stands. The different type values in a single relationship is interesting as you pointed out. In the discussion board none of the specification owners actually answered the question and the commentor's saying it is **true** because of the spec text use of `type(s)` in creating resources in the 409 Conflict section is dubious at best. But because it doesn't explicitly disallow anywhere in the spec as far as I can tell; I would have to agree it is allowed but is atypical. I know `JsonApiFramework` can not handle this scenario correctly and I would bet other JSON API serializer/deserializer SDKs would also not be able to handle it either?

For your case I feel the solution will be at the domain/schema level and avoiding the different concrete types within a single resource's relationship to keep things simple?

**Comment by laazik** [comment]
I'll have to think about this. One option is that I implement the whole thing for a singular use case (it's a pub-sub scenario where data is fetch from MQ and pushed to Drupal), or figure something else out.

Will close this for now, but would be good to have this available as reference, should someone else run into this in the future :).
